version: '3'

services:
  prometheus-rules-generator:
    image: docker.io/mikefarah/yq:latest
    volumes:
      - ../../contrib/prometheus:/workdir:Z
    entrypoint: sh
    command:
      - -c
      - "yq .objects[0].spec /workdir/recording-rules-resource.yml > /workdir/recording-rules.yml"
    userns_mode: host
    user: root

  prometheus:
    image: quay.io/prometheus/prometheus:latest
    ports:
      - "${PROMETHEUS_HOST_PORT:-9090}:9090"
    volumes:
      - ./local_prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:Z
      - ../../contrib/prometheus:/etc/prometheus/contrib:Z
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-remote-write-receiver'
    depends_on:
      prometheus-rules-generator:
        condition: service_completed_successfully

  ubi8:
    build:
      context: ../../
      dockerfile: ./integration-tests/docker/Dockerfile.ubi8
    volumes:
      - ../../:/workspace/host-metering:Z
    environment:
      - IS_IN_CONTAINER=true
    command: /bin/sh -c "while sleep 1000; do :; done"

  ubi9:
    build:
      context: ../../
      dockerfile: ./integration-tests/docker/Dockerfile.ubi9
    volumes:
      - ../../:/workspace/host-metering:Z
    environment:
      - IS_IN_CONTAINER=true
    command: /bin/sh -c "while sleep 1000; do :; done"

  ubi10:
    build:
      context: ../../
      dockerfile: ./integration-tests/docker/Dockerfile.ubi10
    volumes:
      - ../../:/workspace/host-metering:Z
    environment:
      - IS_IN_CONTAINER=true
    command: /bin/sh -c "while sleep 1000; do :; done"
