apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: host-metering-rules-template
objects:
- apiVersion: monitoring.coreos.com/v1
  kind: PrometheusRule
  metadata:
    labels:
      tenant: rhel
    name: host-metering-recording-rules
  spec:
    groups:
      - name: host-metering
        interval: 10m
        limit: 0
        rules:
          - record: min_system_cpu_logical_count:10m
            expr: |
              min_over_time(
                system_cpu_logical_count{
                product=~".*(^|,)(204)($|,).*",
                billing_model="marketplace",
                support=~"Premium|Standard|Self-Support|None|"
                }[10m]
              )
            labels:
              rulesVersion: v0
