apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: host-metering-rules-template
objects:
- apiVersion: monitoring.coreos.com/v1
  kind: PrometheusRule
  metadata:
    labels:
      tenant: rhel
    name: host-metering-recording-rules
  spec:
    groups:
      - name: host-metering
        rules:
          - record: host:usage:workload:cpu_hours1h
            expr:  max by(_id) (sum_over_time(system_cpu_logical_count[1h:10m])) / scalar(count_over_time(vector(1)[1h:10m]))
